In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\08300\Downloads\archive (1)\train.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [3]:
df.shape

(9800, 18)

In [4]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [5]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [6]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales']

In [7]:
# Converting dates to datetime
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
dtype: object

In [8]:
#Replace null values in Postal Code column with Unknown

df['Postal Code'] = df['Postal Code'].astype(str)
df['Postal Code'] = df['Postal Code'].replace('nan', 'Unknown')

df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [9]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:Christopher830!@localhost:5432/olist_db')

df.to_sql('superstore', engine, if_exists='replace', index=False)

800

In [10]:
from sqlalchemy import text

def run_query(sql):
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn)

In [11]:
run_query("""
    SELECT "Region",
        ROUND(SUM("Sales")::numeric, 2) AS total_sales
    FROM superstore
    GROUP BY "Region"
    ORDER BY total_sales DESC
""")

    Region  total_sales
0     West    710219.68
1     East    669518.73
2  Central    492646.91
3    South    389151.46

In [12]:
# Top 10 Products by Sale

run_query("""
    SELECT "Product Name",
        SUM("Sales") AS num_sales
    FROM superstore
    GROUP BY "Product Name"
    ORDER BY num_sales DESC
    LIMIT 10
""")

                                        Product Name  num_sales
0              Canon imageCLASS 2200 Advanced Copier  61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
2  Cisco TelePresence System EX90 Videoconferenci...  22638.480
3       HON 5400 Series Task Chairs for Big and Tall  21870.576
4         GBC DocuBind TL300 Electric Binding System  19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System  19024.500
6               Hewlett Packard LaserJet 3310 Copier  18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...  18374.895
8          GBC DocuBind P400 Electric Binding System  17965.068
9        High Speed Automatic Electric Letter Opener  17030.312

In [13]:
# Sales by Category

run_query("""
    SELECT "Category",
        ROUND(SUM("Sales")::numeric, 2) AS total_sales
    FROM superstore
    GROUP BY "Category"
    ORDER BY total_sales DESC
""")

          Category  total_sales
0       Technology    827455.87
1        Furniture    728658.58
2  Office Supplies    705422.33

In [14]:
# Montly Sales Trend

run_query("""
    SELECT DATE_TRUNC('month', "Order Date") AS month,
           ROUND(SUM("Sales")::numeric, 2) AS monthly_sales
    FROM superstore
    GROUP BY DATE_TRUNC('month', "Order Date")
    ORDER BY month
""")

        month  monthly_sales
0  2015-01-01       14205.71
1  2015-02-01        4519.89
2  2015-03-01       55205.80
3  2015-04-01       27906.86
4  2015-05-01       23644.30
5  2015-06-01       34322.94
6  2015-07-01       33781.54
7  2015-08-01       27117.54
8  2015-09-01       81623.53
9  2015-10-01       31453.39
10 2015-11-01       77907.66
11 2015-12-01       68167.06
12 2016-01-01       18066.96
13 2016-02-01       11951.41
14 2016-03-01       32339.32
15 2016-04-01       34154.47
16 2016-05-01       29959.53
17 2016-06-01       23599.37
18 2016-07-01       28608.26
19 2016-08-01       36818.34
20 2016-09-01       63133.61
21 2016-10-01       31011.74
22 2016-11-01       75249.40
23 2016-12-01       74543.60
24 2017-01-01       18542.49
25 2017-02-01       22978.82
26 2017-03-01       51165.06
27 2017-04-01       38679.77
28 2017-05-01       56656.91
29 2017-06-01       39724.49
30 2017-07-01       38320.78
31 2017-08-01       30542.20
32 2017-09-01       69193.39
33 2017-10-01       59583.03
34 2017-11-01       79066.50
35 2017-12-01       95739.12
36 2018-01-01       43476.47
37 2018-02-01       19921.00
38 2018-03-01       58863.41
39 2018-04-01       35541.91
40 2018-05-01       43825.98
41 2018-06-01       48190.73
42 2018-07-01       44825.10
43 2018-08-01       62837.85
44 2018-09-01       86152.89
45 2018-10-01       77448.13
46 2018-11-01      117938.16
47 2018-12-01       83030.39

In [15]:
# Sales by Segment

run_query("""
    SELECT "Segment",
        ROUND(SUM("Sales")::numeric, 2) AS total_sales
    FROM superstore
    GROUP BY "Segment"
    ORDER BY total_sales DESC
""")

       Segment  total_sales
0     Consumer   1148060.53
1    Corporate    688494.07
2  Home Office    424982.18

In [16]:
region_sales = run_query("""
    SELECT DATE_TRUNC('month', "Order Date") AS month,
           ROUND(SUM("Sales")::numeric, 2) AS monthly_sales
    FROM superstore
    GROUP BY DATE_TRUNC('month', "Order Date")
    ORDER BY month
""")

category_sales = run_query("""
    SELECT "Category",
        ROUND(SUM("Sales")::numeric, 2) AS total_sales
    FROM superstore
    GROUP BY "Category"
    ORDER BY total_sales DESC
""")

segment_sales = run_query("""
    SELECT "Segment",
        ROUND(SUM("Sales")::numeric, 2) AS total_sales
    FROM superstore
    GROUP BY "Segment"
    ORDER BY total_sales DESC
""")

region_sales.to_csv('region_sales.csv', index=False)
category_sales.to_csv('category_sales.csv', index=False)
segment_sales.to_csv('segment_sales.csv', index=False)
df.to_csv('superstore_clean.csv', index=False)

print("All files successfully exported!")

All files successfully exported!

In [18]:
import os
print(os.getcwd())
print(os.listdir())

c:\ProgramData\Archipelago\Players
['category_sales.csv', 'desktop.ini', 'MajorasMaskRecompiled.yaml', 'Ocarina.of.Time.yaml', 'olist_sql_analysis.ipynb', 'Pik.yaml', 'region_sales.csv', 'segment_sales.csv', 'sms.yaml', 'superstore_clean.csv', 'superstore_clean.ipymb.ipynb', 'Templates', 'WAH.yaml', 'ww.yaml']